Repository bar-d/ios-project-manager, pull requests merged in 2022-09, with the labels that each got.

#1 main view 구현
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManager/Extentsion/Array+Extension.swift
  ProjectManager/ProjectManager/Extentsion/Date+Extension.swift
  ProjectManager/ProjectManager/Extentsion/JSONDecoder+Extentsion.swift
  ProjectManager/ProjectManager/Extentsion/UILabel+Extension.swift
  ProjectManager/ProjectManager/Protocol/ReuseIdentifiable.swift
  ProjectManager/ProjectManager/Scene/Main/Controller/MainViewController.swift
  ProjectManager/ProjectManager/Scene/Main/Model/MockToDoItemManager.swift
  ProjectManager/ProjectManager/Scene/Main/Model/ToDoItem.swift
  ProjectManager/ProjectManager/Scene/Main/Model/sample.json
  ProjectManager/ProjectManager/Scene/Main/View/DoingListView/DoingListTableViewCell.swift
  ProjectManager/ProjectManager/Scene/Main/View/DoingListView/DoingListTableViewController.swift
  ProjectManager/ProjectManager/Scene/Main/View/DoneListView/DoneListTableViewCell.swift
  ProjectManager/ProjectManager/Scene/Main/View/DoneListView/DoneListTableViewController.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/MainViewController.swift
  ProjectManager/ProjectManager/Scene/Main/View/ToDoListView/ToDoListTableViewCell.swift
  ProjectManager/ProjectManager/Scene/Main/View/ToDoListView/ToDoListViewController.swift
Labels: feat, refactor, style

#2 feat: 각 DetailViewController Content 구현
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManager/Scene/Main/Model/MockToDoItemManager.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/DoingListView/DoingListDetailViewController.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/DoingListView/DoingListTableViewCell.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/DoingListView/DoingListTableViewController.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/DoneListView/DoneListDetailViewController.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/DoneListView/DoneListTableViewCell.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/DoneListView/DoneListTableViewController.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/ToDoListView/ToDoListDetailViewController.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/ToDoListView/ToDoListTableViewCell.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/ToDoListView/ToDoListViewController.swift
Labels: feat

#3 Detail view 구현 완료
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManager/Scene/Main/View/Common/ToDoComponentsView.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/DoingListView/DoingListDetailViewController.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/DoneListView/DoneListDetailViewController.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/ToDoListView/ToDoListDetailViewController.swift
Labels: feat, refactor

#4 Feat 2/registration view/content view
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManager/Scene/Main/View/MainView/DoingListView/DoingListTableViewController.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/DoneListView/DoneListTableViewController.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/MainViewController.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/RegistrationView/RegistrationViewController.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/ToDoListView/ToDoListViewController.swift
Labels: feat, refactor

#6 feat: timeLimitLabel 빨간색으로 표시 로직 추가
  ProjectManager/ProjectManager/Scene/Main/View/MainView/MainViewController.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/ProjectTableView/ProjectTableView.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/ProjectTableView/ProjectTableViewCell.swift
Labels: feat

#7 리뷰 받은 커멘트 반영
  ProjectManager/ProjectManager/Scene/Main/Model/MockToDoItemManager 2.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainView/ProjectTableView/AlertController.swift
Labels: refactor

#8 Refactor 4 step2review
  ProjectManager/ProjectManager.xcodeproj/project.pbxproj
  ProjectManager/ProjectManager/Model/ItemListCategory.swift
  ProjectManager/ProjectManager/Model/MockData.json
  ProjectManager/ProjectManager/Model/MockToDoItemManager.swift
  ProjectManager/ProjectManager/Model/ProjectType.swift
  ProjectManager/ProjectManager/Model/ToDoItem.swift
  ProjectManager/ProjectManager/Protocol/DataSenable.swift
  ProjectManager/ProjectManager/Scene/Alert/View/AlertViewController.swift
  ProjectManager/ProjectManager/Scene/Alert/ViewModel/AlertViewModel.swift
  ProjectManager/ProjectManager/Scene/Common/MainViewModel.swift
  ProjectManager/ProjectManager/Scene/Common/ToDoComponentsView.swift
  ProjectManager/ProjectManager/Scene/Main/ProjectTableView/Cell/ProjectTableViewCell.swift
  ProjectManager/ProjectManager/Scene/Main/ProjectTableView/ProjectDetailViewController 2.swift
  ProjectManager/ProjectManager/Scene/Main/ProjectTableView/ProjectTableHeaderView.swift
  ProjectManager/ProjectManager/Scene/Main/ProjectTableView/ProjectTableView.swift
  ProjectManager/ProjectManager/Scene/Main/ProjectTableView/ViewModel/ProjectTableViewModel.swift
  ProjectManager/ProjectManager/Scene/Main/View/Common/ToDoViewModel.swift
  ProjectManager/ProjectManager/Scene/Main/View/MainViewController.swift
  ProjectManager/ProjectManager/Scene/Main/ViewModel/MainViewModel.swift
  ProjectManager/ProjectManager/Scene/ProjectDetailView/View/ProjectDetailViewController.swift
  ProjectManager/ProjectManager/Scene/ProjectDetailView/ViewModel/ProjectDetailViewModel.swift
  ProjectManager/ProjectManager/Scene/Registration/View/RegistrationViewController.swift
  ProjectManager/ProjectManager/Scene/Registration/ViewModel/RegistrationViewModel.swift
Labels: refactor, style
